[ tool.gilesbot ]
  [ tool.gilesbot.pull_requests ]
    enabled = true

  [ tool.gilesbot.milestones ]
    enabled = true
    missing_message = "All pull requests require a milestone."
    missing_message_long = "This pull request does not have a milestone assigned to it. Only maintainers can change this, so you don't need to worry about it. :smile:"
    
  [ tool.gilesbot.towncrier_changelog ]
    enabled = true
